# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name=b'Address')),
                ('county', models.CharField(choices=[(b'Carlow', b'Carlow'), (b'Cavan', b'Cavan'), (b'Clare', b'Clare'), (b'Cork', b'Cork'), (b'Donegal', b'Donegal'), (b'Dublin', b'Dublin'), (b'Galway', b'Galway'), (b'Kerry', b'Kerry'), (b'Kildare', b'Kildare'), (b'Kilkenny', b'Kilkenny'), (b'Laois', b'Laois'), (b'Leitrim', b'Leitrim'), (b'Limerick', b'Limerick'), (b'Longford', b'Longford'), (b'Louth', b'Louth'), (b'Mayo', b'Mayo'), (b'Meath', b'Meath'), (b'Monaghan', b'Monaghan'), (b'Offaly', b'Offaly'), (b'Roscommon', b'Roscommon'), (b'Tipperary', b'Tipperary'), (b'Waterford', b'Waterford'), (b'Westmeath', b'Westmeath'), (b'Wexford', b'Wexford'), (b'Wicklow', b'Wicklow')], max_length=10, verbose_name=b'County')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name=b'Price')),
                ('date_of_sale', models.DateField()),
                ('not_full_market', models.BooleanField(choices=[(0, b'No'), (1, b'Yes')], default=1, verbose_name=b'Not Full Market Price')),
            ],
            options={
                'ordering': ['date_of_sale'],
            },
        ),
    ]
